services:
  web:
    volumes:
      - ./docker/dhis-doris.conf:/opt/dhis2/dhis.conf:ro
    depends_on:
      doris-init:
        condition: service_completed_successfully
    networks:
      doris_network:
        ipv4_address: 192.168.100.9

  db:
    networks:
      doris_network:
        ipv4_address: 192.168.100.8

  doris-fe:
    image: apache/doris:fe-${DORIS_VERSION}
    networks:
      doris_network:
        ipv4_address: 192.168.100.10
    ports:
      - "9030:9030"
      - "8030:8030"
    environment:
      #- FE_SERVERS=fe1:127.0.0.1:9010
      #- FE_SERVERS=fe1:doris-fe:9010
      - FE_SERVERS=fe1:192.168.100.10:9010
      - FE_ID=1
    volumes:
      - ./docker/postgresql.jar:/opt/apache-doris/fe/jdbc_drivers/postgresql.jar:ro
      - ./docker/postgresql-42.7.5.jar:/opt/apache-doris/fe/jdbc_drivers/postgresql-42.7.5.jar:ro
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8030/home || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  doris-be:
    image: apache/doris:be-${DORIS_VERSION}
    networks:
      doris_network:
        ipv4_address: 192.168.100.11
    environment:
      - FE_SERVERS=fe1:192.168.100.10:9010
      #- BE_ADDR=127.0.0.1:9050
      - BE_ADDR=192.168.100.11:9050
    ports:
      - 8041:8040
    depends_on:
      doris-fe:
        condition: service_healthy
    volumes:
      - ./docker/postgresql.jar:/opt/apache-doris/be/jdbc_drivers/postgresql.jar:ro
      - ./docker/postgresql-42.7.5.jar:/opt/apache-doris/be/jdbc_drivers/postgresql-42.7.5.jar:ro
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8040/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  doris-init:
    image: alpine:latest
    networks:
      doris_network:
        ipv4_address: 192.168.100.12
    depends_on:
      doris-fe:
        condition: service_healthy
      doris-be:
        condition: service_healthy
    command: >
      sh -c "apk add --no-cache mysql-client &&
             mysql -h192.168.100.10 -P9030 -uroot --protocol=tcp --skip-password -e 'CREATE DATABASE IF NOT EXISTS dhis2;'"

networks:
  doris_network:
    ipam:
      config:
        - subnet: 192.168.100.0/24
