-- Raw login events. One row per recorded login (deduped per user+authType for a short window
-- at write time so PAT/basic-auth request storms do not flood the table).
create table if not exists loginevent (
    logineventid bigint generated by default as identity primary key,
    username     varchar(255) not null,
    timestamp    timestamp without time zone not null,
    authtype     varchar(32)  not null
);

create index if not exists in_loginevent_timestamp on loginevent (timestamp);
create index if not exists in_loginevent_username_timestamp on loginevent (username, timestamp);
create index if not exists in_loginevent_authtype_timestamp on loginevent (authtype, timestamp);

-- Daily rollup produced by the LOGIN_EVENT_CLEANUP job before raw rows older than the
-- retention window are pruned. Survives indefinitely so historical logins/day is preserved.
create table if not exists logineventdaily (
    logindate   date primary key,
    logins      integer not null,
    uniqueusers integer not null
);
