CREATE TABLE dataelementinsightssnapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created TIMESTAMP NOT NULL,
    payload TEXT NOT NULL
);

CREATE INDEX in_dataelementinsightssnapshot_created ON dataelementinsightssnapshot (created);
