-- Query for "Search TE by name with like operator" from TrackerTest
-- This is the query from DHIS2-20655-reduce-async branch that fetches full TrackedEntity
-- data in a single query (vs master which fetches IDs first, then fetches TEs async)
--
-- The test searches for First name (w75KJ2mc4zz) containing "Ines" but there's no matching
-- data enrolled in the tracker program - query still does full scan, returns 0 rows.

EXPLAIN (ANALYZE, VERBOSE, COSTS, BUFFERS, FORMAT JSON)
select te.trackedentityid, te.uid, te.created, te.lastupdated, te.createdatclient, te.lastupdatedatclient, te.inactive, te.potentialduplicate, te.deleted, te.createdbyuserinfo, te.lastupdatedbyuserinfo, te.geometry, te.tet_id, te.tet_uid, te.tet_code, te.tet_name, te.tet_attributevalues, te.tet_allowauditlog, te.tet_enablechangelog, te.te_ou_uid, te.te_ou_code, te.te_ou_name, te.te_ou_path, te.te_ou_attributevalues, po_ou_uid, po_prg_uid from ( select distinct te.trackedentityid as trackedentityid, te.uid as uid, te.created as created, te.lastupdated as lastupdated, te.createdatclient as createdatclient, te.lastupdatedatclient as lastupdatedatclient, te.inactive as inactive, te.potentialduplicate as potentialduplicate, te.deleted as deleted, te.createdbyuserinfo as createdbyuserinfo, te.lastupdatedbyuserinfo as lastupdatedbyuserinfo, ST_AsBinary (te.geometry) as geometry, tet.trackedentitytypeid as tet_id, tet.uid as tet_uid, tet.code as tet_code, tet.name as tet_name, tet.attributevalues as tet_attributevalues, tet.allowauditlog as tet_allowauditlog, tet.enableChangeLog as tet_enablechangelog, te_ou.uid as te_ou_uid, te_ou.code as te_ou_code, te_ou.name as te_ou_name, te_ou.path as te_ou_path, te_ou.attributevalues as te_ou_attributevalues, ou.uid as po_ou_uid, p.uid as po_prg_uid from trackedentity te inner join program p on p.trackedentitytypeid = te.trackedentitytypeid inner join trackedentityprogramowner po on po.programid = '1150449' and po.trackedentityid = te.trackedentityid and p.programid = po.programid inner join organisationunit ou on ou.organisationunitid = po.organisationunitid and ((p.accesslevel in ('OPEN', 'AUDITED') and ou.path like any ( select concat(o.path, '%') from organisationunit o where o.uid in ('DiszpKrYNg8'))) or (p.accesslevel in ('PROTECTED', 'CLOSED') and ou.path like any ( select concat(o.path, '%') from organisationunit o where o.uid in ('DiszpKrYNg8'))) or (p.accesslevel = 'PROTECTED' and exists ( select 1 from programtempowner where programid = p.programid and trackedentityid = te.trackedentityid and userid = 1688491 and extract(epoch from validtill) - extract(epoch from now()::timestamp) > 0))) join organisationunit te_ou on te.organisationunitid = te_ou.organisationunitid join trackedentitytype tet on te.trackedentitytypeid = tet.trackedentitytypeid left join trackedentityattributevalue as "w75KJ2mc4zz" on "w75KJ2mc4zz".trackedentityid = te.trackedentityid and "w75KJ2mc4zz".trackedentityattributeid = 1153532 where lower("w75KJ2mc4zz".value) like '%ines%' and te.deleted is false and exists ( select en.trackedentityid from enrollment en where en.trackedentityid = te.trackedentityid and en.programid = '1150449' and en.deleted is false) order by te.trackedentityid desc limit 6 offset 0) te order by te.trackedentityid desc;
