update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.AggregateDataExchangeJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.AggregateDataExchangeJobParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.AnalyticsJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.AnalyticsJobParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.ContinuousAnalyticsJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.ContinuousAnalyticsJobParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.DataIntegrityJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.DataIntegrityJobParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.DataSynchronizationJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.DataSynchronizationJobParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.DisableInactiveUsersJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.DisableInactiveUsersJobParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.EventProgramsDataSynchronizationJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.EventProgramsDataSynchronizationJobParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.LockExceptionCleanupJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.LockExceptionCleanupJobParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.MetadataSyncJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.MetadataSyncJobParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.MonitoringJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.MonitoringJobParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.PredictorJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.PredictorJobParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.PushAnalysisJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.PushAnalysisJobParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.SqlViewUpdateParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.SQLViewUpdateParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.SmsJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.SmsJobParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.TestJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.TestJobParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.TrackerProgramsDataSynchronizationJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.TrackerProgramsDataSynchronizationJobParametersDeserializer$CustomJobParameters';
update jobconfiguration set jsonbjobparameters = jsonb_build_array('org.hisp.dhis.scheduling.parameters.TrackerTrigramIndexJobParameters', jsonbjobparameters -> 1)
    where jsonbjobparameters ->> 0 = 'org.hisp.dhis.scheduling.parameters.jackson.TrackerTrigramIndexJobParametersDeserializer$CustomJobParameters';