#!/usr/bin/env python3
"""
DHIS2 User Group Generator for Performance Testing

Generates user group definitions for performance testing.
Outputs DHIS2 metadata JSON format that can be POSTed to /api/metadata.

The UIDs are deterministic (seeded random) so they match between
usergroups.json and the user files generated by generate_users.py.

Usage:
    python generate_usergroups.py --output usergroups.json

Author: Generated for DHIS2 performance testing
"""

import argparse
import json
import random
import string
import sys

# =============================================================================
# UID Generation (DHIS2 compatible, deterministic)
# =============================================================================

UID_ALPHABET = string.ascii_letters + string.digits
UID_FIRST_CHAR = string.ascii_letters  # First char must be letter

SEED = 20613  # Fixed seed for deterministic UIDs


def generate_uid(rng: random.Random) -> str:
    """Generate a valid DHIS2 UID (11 alphanumeric chars, first must be letter)."""
    first = rng.choice(UID_FIRST_CHAR)
    rest = "".join(rng.choices(UID_ALPHABET, k=10))
    return first + rest


# =============================================================================
# User Group Definitions
# =============================================================================

USER_GROUP_DEFS = [
    {"name": "Performance Test - All Users", "code": "PERF_ALL_USERS"},
    {"name": "Performance Test - Data Entry", "code": "PERF_DATA_ENTRY"},
    {"name": "Performance Test - Data Viewers", "code": "PERF_DATA_VIEWERS"},
    {"name": "Performance Test - District Users", "code": "PERF_DISTRICT_USERS"},
    {"name": "Performance Test - Regional Team", "code": "PERF_REGIONAL_TEAM"},
    {"name": "Performance Test - Facility Managers", "code": "PERF_FACILITY_MANAGERS"},
    {"name": "Performance Test - Admin Team", "code": "PERF_ADMIN_TEAM"},
    {"name": "Performance Test - Pilot Group", "code": "PERF_PILOT_GROUP"},
    {"name": "Performance Test - System Admins", "code": "PERF_SYSTEM_ADMINS"},
    {"name": "Performance Test - Super Admins", "code": "PERF_SUPER_ADMINS"},
]


def generate_usergroups() -> list[dict]:
    """Generate user group definitions with deterministic UIDs."""
    rng = random.Random(SEED)
    groups = []
    for defn in USER_GROUP_DEFS:
        uid = generate_uid(rng)
        groups.append({
            "id": uid,
            "name": defn["name"],
            "code": defn["code"],
        })
    return groups


def main():
    parser = argparse.ArgumentParser(
        description="Generate DHIS2 user group definitions for performance testing.",
    )
    parser.add_argument(
        "--output", "-o",
        type=str,
        default="usergroups.json",
        help="Output file path (default: usergroups.json)",
    )
    parser.add_argument(
        "--print-config",
        action="store_true",
        help="Print the generated UIDs for use in generate_users.py",
    )

    args = parser.parse_args()

    groups = generate_usergroups()

    if args.print_config:
        print("# User group UIDs (paste into generate_users.py USER_GROUP_CONFIG):")
        weights = [117730, 69524, 15760, 9385, 8739, 373, 174, 50, 3, 2]
        for g, w in zip(groups, weights):
            print(f'    {{"id": "{g["id"]}", "name": "{g["name"]}", "weight": {w}}},')
        return

    data = {"userGroups": groups}

    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

    print(f"Generated {len(groups)} user groups to {args.output}", file=sys.stderr)
    for g in groups:
        print(f"  {g['id']}  {g['name']} ({g['code']})", file=sys.stderr)


if __name__ == "__main__":
    main()
