services:
  web:
    volumes:
      - ./config/dhis2_home/dhis-clickhouse.conf:/opt/dhis2/dhis.conf:ro
    networks:
      - clickhouse_network
      - default
  db:
    networks:
      - clickhouse_network
      - default

  test:
    networks:
      - clickhouse_network
      - default
    environment:
      DHIS2_E2E_TEST_ARGS: "--activate-profiles analytics -Danalytics.api.query.params=skipTrackedEntities=false&skipOutliers=true -Ddhis2.analytics.datasource=clickhouse"

