version: "3.8"

services:
  test:
    build: .
    stdin_open: true
    environment:
      RP_UUID: ${RP_UUID}
    command: ./wait-for-it.sh web:8080 -t 0 -- mvn test --batch-mode --no-transfer-progress -Dinstance.url=http://web:8080/api -Dtest.cleanup=false -Duser.default.username=admin -Duser.default.password=district -Dtest.track_called_endpoints=true -Drp.enable=true -Drp.launch=api_test_2.39 -Drp.attributes=version:2.39;
    depends_on:
      - web
