version: "3.8"

services:
  web:
    image: "${DHIS2_IMAGE:-dhis2/core-dev:local}"
    # Only container ports are specified, as the E2E tests run in parallel in Jenkins and using explicit host ports causes collision
    ports:
      - "8080" # DHIS2
      - "8081" # Debugger: connect using commandline flag -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081
    volumes:
      - ./config/dhis2_home/dhis.conf:/opt/dhis2/dhis.conf:ro
    environment:
      JAVA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8081"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgis/postgis:10-2.5-alpine
    command: postgres -c max_locks_per_transaction=100
    restart: unless-stopped
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: &postgres_password dhis
      PGPASSWORD: *postgres_password # needed by psql in healthcheck
    healthcheck:
      test: [ "CMD-SHELL", "psql --no-password --quiet --username $$POSTGRES_USER postgres://127.0.0.1/$$POSTGRES_DB -p 5432 --command \"SELECT 'ok'\" > /dev/null" ]
      start_period: 120s
      interval: 1s
      timeout: 3s
      retries: 5

  redis:
    image: redis:5.0.5-alpine
    volumes:
      - ./config/redis/redis.conf:/usr/local/etc/redis.conf
    ports:
      - "6379"

  selenium:
    image: 'selenium/standalone-chrome:latest'
    ports:
      - '4444'
      - '7900'
