
services:
  test:
    build: .
    stdin_open: true
    environment:
      DHIS2_E2E_TEST_ARGS: "${DHIS2_E2E_TEST_ARGS:-}" # to for example pass a profile like -Panalytics
      DHIS2_E2E_TEST_USER_ARGS: "${DHIS2_E2E_TEST_USER_ARGS:--Duser.default.username=admin -Duser.default.password=district}" # adjust if you for example use a demo DB dump instead of the default empty DB
    command: sh -c './wait-for-it.sh web:8080 -t 600 -- mvn test $$DHIS2_E2E_TEST_ARGS $$DHIS2_E2E_TEST_USER_ARGS --batch-mode --no-transfer-progress -Dinstance.url=http://web:8080/api -Dtest.cleanup=false -Dtest.track_called_endpoints=true -Drp.enable=true -Drp.launch=api_test_master -Drp.attributes=version:master;'
    volumes:
      - surefire-reports:/target/surefire-reports
    depends_on:
      - web

  reports-processor:
    profiles: ["reports"]
    image: python:3.11-slim
    volumes:
      - surefire-reports:/reports
      - ./config/scripts/process-test-reports.sh:/process-test-reports.sh:ro
    environment:
      GIT_AUTHOR_NAME: ${GIT_AUTHOR_NAME:-DHIS2 Test Bot}
      GIT_AUTHOR_EMAIL: ${GIT_AUTHOR_EMAIL:-test-bot@dhis2.org}
      GIT_COMMITTER_NAME: ${GIT_COMMITTER_NAME:-DHIS2 Test Bot}
      GIT_COMMITTER_EMAIL: ${GIT_COMMITTER_EMAIL:-test-bot@dhis2.org}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GPG_PRIVATE_KEY: ${GPG_PRIVATE_KEY}
      GPG_KEY_ID: ${GPG_KEY_ID}
      GPG_PASSPHRASE: ${GPG_PASSPHRASE}
      DB_TYPE: ${DB_TYPE:-postgres}
      TEST_TYPE: ${TEST_TYPE:-e2e}
    command: ["/process-test-reports.sh"]

volumes:
  surefire-reports:
