version: "3.8"

services:
  db:
    volumes:
      - "${DHIS2_E2E_TEST_DUMP_PATH}:/docker-entrypoint-initdb.d/"

  test:
    environment:
      DHIS2_E2E_TEST_ARGS: "--activate-profiles analytics"
      DHIS2_E2E_TEST_USER_ARGS: "-Duser.admin.username=admin -Duser.admin.password=district"
