on: [push]
name: notify
jobs:
  dont-fail:
    runs-on: ubuntu-latest
    steps:
      - name: pass
        run: exit 0
  always-fail:
    runs-on: ubuntu-latest
    steps:
    - name: fail
      run: exit 1
  post-slack:
    runs-on: ubuntu-latest
    if: |
      always() &&
      contains(needs.*.result, 'failure')
    needs: [dont-fail,always-fail]
    steps:
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_USERNAME: 'GitHub'
          SLACK_WEBHOOK: ${{ secrets.SLACK_BACKEND_WEBHOOK }}
          SLACK_CHANNEL: 'gintare'
          SLACK_MESSAGE: 'Latest test run on master failed and needs investigation :detective-duck:'
